try{
    throw new Error('Gerando um erro Gen√©rico!')
}
catch(e){
    console.error(`${e.name}: ${e.message}`);
}